esphome:
  name: bonn_temp
  platform: ESP8266
  board: d1_mini

logger:

ota:

wifi:
  ssid: "WLAN-458941"
  password: "36278376866873849593"
  domain: ".home"

mqtt:
  broker: 10.10.2.5
  username: bonn_dht_esphome
  password: uFBRuq9ovPVKp4t4ka

sensor:
  - platform: dht12
    temperature:
      name: "Bonn Temperature"
      accuracy_decimals: 3
    humidity:
      name: "Bonn Humidity"
      accuracy_decimals: 3
    update_interval: 10min

i2c:
  sda: D2
  scl: D1
  scan: True
  id: bus_a
